### ISSUE TITLE
Hamburger button does not work.

### ISSUE THREAD

**Issue by Nebelung-Dev** [NocturaProxy/Frontend#12]
When you click on it it disappears after a second

**Comment by Riftriot** [comment]
I don't get the error, did you do anything special to cause it?

**Comment by cohenerickson** [comment]
I've had this happen to me as well, not sure what is causing it, appears to fix itself after a reload?

**Comment by MadjikDotPng** [comment]
this happens randomly sometimes idk

**Comment by Sylvie-TN** [comment]
Fixed
