### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Thesecondalthowcool** [NocturaProxy/Frontend#13]
Could you make a lite version of this. On Replit, it's to big and gets disabled. Also for probably many other deployment services this proxy would be to big. So making a lite version of this would be very helpful.

**Comment by illusionTBA** [comment]
no, replit and other services dont allow these types of sites in the first place.

**Comment by Riftriot** [comment]
illusion is right, most free deployment sites don't allow web proxies, although we will take it into consideration for the near future, it's mostly our web code editor (monaco) taking up a lot of the space
